version: 2.1


orbs:
  docker: circleci/docker@2.7.1  # Ensure this is the latest version
jobs:
  build:
    docker:
      - image: jonw123test.jfrog.io/docker-remote/cimg/android:2021.08.1
        auth:
          username: austinf
          password: $ARTIFACTORY_PASSWORD

