version: 2.1

#orbs:
 # docker: circleci/docker@2.7.1  # Ensure this is the latest version

jobs:
  build:
    docker:
      - image: jonw123test.jfrog.io/docker-remote/cimg/android:stable
        auth:
          username: $ARTIFACTORY_USER
          password: $ARTIFACTORY_PASSWORD

      # Your build steps
      - run:
          name: Additional Commands
          command: echo "Running additional commands post Docker image pull"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
