version: 2.1

orbs:
  docker: circleci/docker@2.7.1  # Ensure this is the latest version

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker

      # Login to Artifactory Docker Registry
      - run:
          name: Login to Artifactory
          command: |
            echo "$ARTIFACTORY_PASSWORD" | docker login $ARTIFACTORY_URL --username $ARTIFACTORY_USER --password-stdin

      # Pull the custom Docker image from Artifactory
      - run:
          name: Pull Docker Image from Artifactory
          command: docker pull jonw123test.jfrog.io/docker-remote/nginx:latest

      # Here, you can add commands to use the Docker image
      - run:
          name: Use Docker Image
          command: |
            # Example command, replace with actual commands to run inside the Docker image
            docker run jonw123test.jfrog.io/docker-remote/nginx:latest

      # Your build steps
      - run:
          name: Additional Commands
          command: echo "Running additional commands post Docker image pull"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
