name: Build and Tag Docker Image
on: [push]
jobs:
  build-and-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ secrets.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
          JF_USER: austinf
      - name: Build Tag and push Docker Image
        env:
          IMAGE_NAME: jonw123test.jfrog.io/docker-local/emtech-supply-chain-evals-jfrog:${{ github.run_number }}
        run: |
          jf config show
          jf docker pull jonw123test.jfrog.io/docker-remote/nginx:latest
          # jf docker build -t $IMAGE_NAME .
          # jf docker push $IMAGE_NAME
      - name: Publish Build info With JFrog CLI
        env:
          # Generated and maintained by GitHub
          JFROG_CLI_BUILD_NAME: emtech-supply-chain-evals-jfrog
          # JFrog organization secret
          JFROG_CLI_BUILD_NUMBER : ${{ github.run_number }}
        run: |
          # Export the build name and build nuber
          # Collect environment variables for the build
          jf rt build-collect-env
          # Collect VCS details from git and add them to the build
          jf rt build-add-git
          # Publish build info
          jf rt build-publish
